# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tidytuesday003',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/tidytuesday003',
                'lib_path': 'tidytuesday003'},
  'syms': {'tidytuesday003.core': {'tidytuesday003.core.foo': ('core.html#foo', 'tidytuesday003/core.py')}}}
